### ISSUE TITLE
Any plan to integrate this package into d3fc ?

### ISSUE THREAD

**Issue by scalastic** [d3fc/d3fc-brush#2]
Regards

**Comment by ColinEberhardt** [comment]
That's a very good point! I'd been meaning to integrate this when I had a chance to implement d3fc-zoom, but I guess I should just go ahead anyway. 

I'll sort that out shortly.

**Comment by ColinEberhardt** [comment]
This is now available as part of d3fc 12.3.0 https://github.com/d3fc/d3fc/releases/tag/v12.3.0

**Comment by scalastic** [comment]
@ColinEberhardt 
Many thanks , gona brush now :)
